{{- $cluster_name := .Values.cluster_name }}
{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .repo.path }}
    repoURL: {{ .repo.url }}
    targetRevision: {{ .repo.ref | quote }}
    helm:
      valueFiles:
        - ../../conf/common/values-common.yaml
        - ../../conf/aggregations/values-non-prod.yaml
        - ../../conf/envs/{{ $cluster_name }}
  syncPolicy:
    syncOptions:
      - "CreateNamespace=false"
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}