cluster_name: prod-nasa/dca19.yaml
apps:
  - name: ntc
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/ntc'
      ref: '22.3'
  - name: wordpress
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/wordpress'
      ref: '22.3'
