apps:
  - name: ntc
    project: ntc
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/nginx_chart'
      path: '.'
      ref: master
    helm:
      valuesFiles:
        - values-fra41-eks02.yaml
