apps:
  - name: ntc
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/ntc'
      ref: main
    helm:
      valuesFiles:
        - ../../conf/common/values-common.yml
        - ../../conf/aggregations/values-eu.yml
        - ../../conf/aggregations/values-prod.yml
        - ../../conf/envs/prod-eu/values-local-minikube.yaml
  - name: wordpress
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/wordpress'
      ref: main
    helm:
      valuesFiles:
        - /conf/common/values-common.yml
        - /conf/aggregations/values-eu.yml
        - /conf/aggregations/values-prod.yml
        - /conf/envs/prod-eu/values-local-minikube.yaml
