apps:
  - name: ntc
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/ntc'
      ref: main
  - name: wordpress
    project: default
    namespace: testnm
    repo:
      url: 'https://github.com/furmanyk/cm_poc_helm'
      path: 'charts/wordpress'
      ref: main
