apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: headAppSet
spec:
  generators:
  - list:
      elements:
      - name: ntc
        repourl: 'https://github.com/furmanyk/cm_poc_helm'
        repopath: 'charts/ntc'
        reporef: main
      - name: wordpress
        repourl: 'https://github.com/furmanyk/cm_poc_helm'
        repopath: 'charts/wordpress'
        reporef: main
  template:
    metadata:
      name: '{{name}}'
    spec:
      source:
        repoURL: {{repourl}}
        targetRevision: {{reporef}}
        path: {{repopath}}
        helm:
      valuesFiles:
        - ../../conf/common/values-common.yml
        - ../../conf/aggregations/values-eu.yml
        - ../../conf/aggregations/values-prod.yml
        - ../../conf/envs/prod-eu/values-local-minikube.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: testnm

# apps:
#   - name: ntc
#     project: default
#     namespace: testnm
#     repo:
#       url: 'https://github.com/furmanyk/cm_poc_helm'
#       path: 'charts/ntc'
#       ref: main
#     helm:
#       valuesFiles:
#         - ../../conf/common/values-common.yml
#         - ../../conf/aggregations/values-eu.yml
#         - ../../conf/aggregations/values-prod.yml
#         - ../../conf/envs/prod-eu/values-local-minikube.yaml
#   - name: wordpress
#     project: default
#     namespace: testnm
#     repo:
#       url: 'https://github.com/furmanyk/cm_poc_helm'
#       path: 'charts/wordpress'
#       ref: main
#     helm:
#       valuesFiles:
#         - ../../conf/common/values-common.yml
#         - ../../conf/aggregations/values-eu.yml
#         - /conf/aggregations/values-prod.yml
#         - /conf/envs/prod-eu/values-local-minikube.yaml
