{{- $pullSecret := include "imagePullSecret" . -}}
{{- $pullSecretOverride := include "imagePullSecretOverride" . -}}
{{- range .Values.projects }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: {{ .namespace }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .useRoRegistry }}
  .dockerconfigjson: {{ $pullSecretOverride }}
  {{- else }}
  .dockerconfigjson: {{ $pullSecret }}
  {{- end }}
{{- end }}
