{{- $CpuLimit := .Values.defaultsLimits.limit.cpu }}
{{- $CpuRequest := .Values.defaultsLimits.request.cpu }}
{{- $MemoryLimit := .Values.defaultsLimits.limit.memory}}
{{- $MemoryRequest := .Values.defaultsLimits.request.memory }}
{{- range .Values.projects }}
{{- if .useLimitRange}}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}-limit-range
  namespace: {{ .namespace }}
spec:
  limits:
  {{- if .limits}}
  - default:
      {{- if .limits.default }}
      cpu: {{ .limits.default.cpu | default $CpuLimit | quote }} 
      memory: {{ .limits.default.memory | default $MemoryLimit|  quote }} 
      {{- else }}
      cpu: {{ $CpuLimit | quote }} 
      memory: {{ $MemoryLimit | quote }} 
      {{- end }}
    defaultRequest:
      {{- if .limits.request }}
      cpu: {{ .limits.request.cpu | default $CpuRequest | quote }} 
      memory: {{ .limits.request.memory | default $MemoryRequest | quote }}
      {{- else }}
      cpu: {{ $CpuRequest | quote }} 
      memory: {{ $MemoryRequest | quote }}
      {{- end }}
  {{- else }}
  - default:
      cpu: {{ $CpuLimit }}
      memory: {{ $MemoryLimit }}
    defaultRequest:
      cpu: {{ $CpuRequest }}
      memory: {{ $MemoryRequest }}
  {{- end }}
    type: Container
{{- end }}  
{{- end }}
