---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: features-ci
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: 'features-ci-*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
